name: weather-cache-server
version: 0.1.0.0
github: "githubuser/weather-cache-server"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/weather-cahche-server#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - warp
    - servant
    - servant-server
    - servant-client
    - servant-openapi3
    - servant-swagger-ui
    - async
    - time
    - split
    - text
    - bytestring
    - containers
    - transformers
    - mtl
    - hashmap
    - aeson
    - stm
    - http-client-tls
    - http-types
    - persistent-spatial

executables:
  weather-cahche-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - weather-cache-server
      - optparse-applicative

      - envparse
      - dhall
      - time
      - split
      - text
      - transformers
tests:
  weather-cahche-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - weather-cache-server
